query($page: Int, $mediaType: MediaType) {
    Page(page: $page, perPage: 50) {
        pageInfo {
            total
            perPage
            currentPage
            lastPage
            hasNextPage
        },
        mediaList (userId: 150148, $mediaType) {
            id,
            score,
            status,
            progress,
            media {
                id,
                description,
                episodes,
                status,
                type,
                title {
                    romaji
                    english
                    native
                },
                coverImage {
                    large
                    medium
                }
            }
        }
    }
}